name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u majst01 -p ${{ secrets.PACKAGE_REPO_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/metal-pod/droptailer:latest
        docker push docker.pkg.github.com/metal-pod/droptailer:latest
      
